---

- name: add /etc/fail2ban/jail.local
  template: >
    src=etc-fail2ban-jail.local.j2
    dest=/etc/fail2ban/jail.local
    owner=root group=root mode=0644
  notify:
    - fail2ban restart
  tags:
    - common:fail2ban

- name: add /etc/fail2ban/filter.d/nginx.conf
  copy: >
    src=etc-fail2ban-filter.d-nginx.conf
    dest=/etc/fail2ban/filter.d/nginx.conf
    owner=root group=root mode=0644
  notify:
    - fail2ban restart
  tags:
    - common:fail2ban