---

- name: add /etc/iptables.rules
  template: >
    src=etc-iptables.rules
    dest=/etc/iptables.rules
    owner=root group=root mode=0644
  notify:
    - load iptables
  tags:
    - common:iptables

- name: add /etc/if-pre-up.d and /etc/if-post-down.d iptables-restore
  copy: >
    src=etc-network-if-iptables-restore
    dest=/etc/network/{{ item }}/iptables-restore
    owner=root group=root mode=0755
  with_items:
    - if-pre-up.d
    - if-post-down.d
  notify:
    - load iptables
  tags:
    - common:iptables