---

- name: reconfigure locales
  shell: dpkg-reconfigure locales

- name: update-locale utf8
  shell: update-locale LANG={{ common.serverLocale }}

- name: add /etc/apt/apt.conf.d/10periodic
  copy: >
    src=etc-apt-apt.conf.d-10periodic
    dest=/etc/apt/apt.conf.d/10periodic
    owner=root group=root mode=0644

- name: add /etc/apt/apt.conf.d/50unattended-upgrades
  template: >
    src=etc-apt-apt.conf.d-50unattended-upgrades
    dest=/etc/apt/apt.conf.d/50unattended-upgrades
    owner=root group=root mode=0644

- name: install/ensure core packages
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items: common.packages.core

- name: install additional common packages
  apt: pkg={{ item }} state=installed
  with_items: common.packages.additional

- include: tunning.yml
- include: pam.yml
- include: ntp.yml
- include: ssh.yml
- include: iptables.yml
- include: limits.yml
- include: fail2ban.yml
