---

- name: add /etc/timezone
  lineinfile: >
    dest=/etc/timezone
    regexp="^"
    line='{{ common.timezone }}'
    state=present
  notify: timezone apply

- name: add ntp servers to /etc/ntp.conf
  template: >
    src=etc-ntp.conf.j2
    dest=/etc/ntp.conf
    owner=root group=root mode=0644
  notify: ntp restart